//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieAnalyzer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int MovieId { get; set; }
        public string Name { get; set; }
        public int Rank { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public long AccumulatedSales { get; set; }
        public int AccumulatedAudience { get; set; }
        public int NoOfScreens { get; set; }
        public System.DateTime Date { get; set; }
    }
}
